Repository WorkDuo/WorkDuo_dev, pull requests merged in 2022-09, with the labels that each got.

#25 Gyubin
  build.gradle
  src/main/java/com/workduo/WorkduoApplication.java
  src/main/java/com/workduo/area/common/controller/AreaController.java
  src/main/java/com/workduo/common/CommonResponse.java
  src/main/java/com/workduo/configuration/s3/AwsS3Configuration.java
  src/main/java/com/workduo/error/global/exception/CustomS3Exception.java
  src/main/java/com/workduo/error/global/type/GlobalExceptionType.java
  src/main/java/com/workduo/group/gropcontent/controller/GroupContentController.java
  src/main/java/com/workduo/group/gropcontent/dto/creategroupcontent/CreateGroupContent.java
  src/main/java/com/workduo/group/gropcontent/dto/detailgroupcontent/DetailGroupContent.java
  src/main/java/com/workduo/group/gropcontent/dto/detailgroupcontent/DetailGroupContentDto.java
  src/main/java/com/workduo/group/gropcontent/dto/detailgroupcontent/GroupContentImageDto.java
  src/main/java/com/workduo/group/gropcontent/entity/GroupContent.java
  src/main/java/com/workduo/group/gropcontent/entity/GroupContentImage.java
  src/main/java/com/workduo/group/gropcontent/entity/GroupContentLike.java
  src/main/java/com/workduo/group/gropcontent/entity/GroupContentLikeId.java
  src/main/java/com/workduo/group/gropcontent/repository/GroupContentImageRepository.java
  src/main/java/com/workduo/group/gropcontent/repository/GroupContentLikeRepository.java
  src/main/java/com/workduo/group/gropcontent/repository/query/GroupContentQueryRepository.java
  src/main/java/com/workduo/group/gropcontent/repository/query/impl/GroupContentQueryRepositoryImpl.java
  src/main/java/com/workduo/group/gropcontent/service/GroupContentService.java
  src/main/java/com/workduo/group/gropcontent/service/impl/GroupContentServiceImpl.java
  src/main/java/com/workduo/group/group/controller/GroupController.java
  src/main/java/com/workduo/group/group/entity/GroupCreateMember.java
  src/main/java/com/workduo/group/group/entity/GroupCreateMemberId.java
  src/main/java/com/workduo/group/group/repository/GroupCreateMemberRepository.java
  src/main/java/com/workduo/group/group/service/impl/GroupServiceImpl.java
  src/main/java/com/workduo/group/groupcontentlike/entity/GroupContentLike.java
  src/main/java/com/workduo/util/AwsS3Utils.java
  src/main/resources/application-dev.properties
  src/main/resources/application.yml
  src/test/java/com/workduo/group/group/service/GroupServiceTest.java
  src/test/java/com/workduo/group/groupcontent/GroupContentServiceTest.java
Labels: ☘️ 기능추가, 🌈 테스트 코드 작성

#27 그룹 리스트, 그룹 참여자 리스트 서비스, 컨트롤러 테스트 코드 작성
  src/main/java/com/workduo/group/gropcontent/dto/detailgroupcontent/GroupContentCommentDto.java
  src/main/java/com/workduo/group/gropcontent/dto/detailgroupcontent/GroupContentDto.java
  src/main/java/com/workduo/group/gropcontent/dto/detailgroupcontent/GroupContentImageDto.java
  src/main/java/com/workduo/group/group/dto/GroupParticipantsDto.java
  src/main/java/com/workduo/group/group/dto/ListGroup.java
  src/main/java/com/workduo/group/group/repository/query/GroupQueryRepository.java
  src/main/java/com/workduo/group/group/repository/query/impl/GroupQueryRepositoryImpl.java
  src/main/java/com/workduo/group/group/service/impl/GroupServiceImpl.java
  src/test/java/com/workduo/group/group/controller/GroupControllerTest.java
  src/test/java/com/workduo/group/group/service/GroupServiceTest.java
  src/test/java/com/workduo/group/groupcontent/controller/GroupContentControllerTest.java
  src/test/java/com/workduo/group/groupcontent/service/GroupContentServiceTest.java
Labels: 🌈 테스트 코드 작성

#28 Gyubin
  src/main/java/com/workduo/error/group/type/GroupErrorCode.java
  src/main/java/com/workduo/group/gropcontent/controller/GroupContentController.java
  src/main/java/com/workduo/group/gropcontent/dto/updategroupcontent/UpdateContent.java
  src/main/java/com/workduo/group/gropcontent/entity/GroupContent.java
  src/main/java/com/workduo/group/gropcontent/repository/GroupContentLikeRepository.java
  src/main/java/com/workduo/group/gropcontent/service/GroupContentService.java
  src/main/java/com/workduo/group/gropcontent/service/impl/GroupContentServiceImpl.java
  src/test/java/com/workduo/group/groupcontent/controller/GroupContentControllerTest.java
  src/test/java/com/workduo/group/groupcontent/service/GroupContentServiceTest.java
Labels: ☘️ 기능추가, 🌈 테스트 코드 작성

#29 맴버 컨탠트 생성 API 구현(테스트)
  src/main/java/com/workduo/configuration/security/SecurityConfiguration.java
  src/main/java/com/workduo/configuration/security/error/CustomNotAuthentication.java
  src/main/java/com/workduo/configuration/security/error/CustomNotAuthorization.java
  src/main/java/com/workduo/error/global/GlobalExceptionController.java
  src/main/java/com/workduo/error/global/handler/GlobalExceptionHandler.java
  src/main/java/com/workduo/member/content/controller/MemberContentController.java
  src/main/java/com/workduo/member/content/dto/ContentCreate.java
  src/main/java/com/workduo/member/content/entity/MemberContent.java
  src/main/java/com/workduo/member/content/repository/MemberContentRepository.java
  src/main/java/com/workduo/member/content/service/MemberContentService.java
  src/main/java/com/workduo/member/content/service/impl/MemberContentServiceImpl.java
  src/main/java/com/workduo/member/contentimage/entitiy/MemberContentImage.java
  src/main/java/com/workduo/member/contentimage/repository/MemberContentImageRepository.java
  src/main/java/com/workduo/member/member/service/impl/MemberServiceImpl.java
  src/test/java/com/workduo/member/content/controller/MemberContentControllerTest.java
  src/test/java/com/workduo/member/content/service/impl/MemberContentServiceImplTest.java
Labels: ☘️ 기능추가, 🐛 Bug, 🌈 테스트 코드 작성

#31 그룹 피드 댓글 리스트, 그룹 피드 댓글 작성 기능 구현
  src/main/java/com/workduo/error/group/type/GroupErrorCode.java
  src/main/java/com/workduo/group/gropcontent/controller/GroupContentController.java
  src/main/java/com/workduo/group/gropcontent/dto/createGroupContentComment/CreateComment.java
  src/main/java/com/workduo/group/gropcontent/dto/detailgroupcontent/DetailContentComment.java
  src/main/java/com/workduo/group/gropcontent/dto/updategroupcontentcomment/UpdateComment.java
  src/main/java/com/workduo/group/gropcontent/entity/GroupContentComment.java
  src/main/java/com/workduo/group/gropcontent/repository/GroupContentCommentRepository.java
  src/main/java/com/workduo/group/gropcontent/repository/query/impl/GroupContentQueryRepositoryImpl.java
  src/main/java/com/workduo/group/gropcontent/service/GroupContentService.java
  src/main/java/com/workduo/group/gropcontent/service/impl/GroupContentServiceImpl.java
  src/main/java/com/workduo/group/group/repository/query/impl/GroupQueryRepositoryImpl.java
  src/test/java/com/workduo/group/groupcontent/controller/GroupContentControllerTest.java
  src/test/java/com/workduo/group/groupcontent/service/GroupContentServiceTest.java
Labels: ☘️ 기능추가, 🌈 테스트 코드 작성

#33 멤버컨탠트 상세페이지 Api 작성
  src/main/java/com/workduo/configuration/security/SecurityConfiguration.java
  src/main/java/com/workduo/error/member/type/MemberErrorCode.java
  src/main/java/com/workduo/member/commentlike/entity/MemberContentCommentLike.java
  src/main/java/com/workduo/member/content/controller/MemberContentController.java
  src/main/java/com/workduo/member/content/dto/MemberContentCommentDto.java
  src/main/java/com/workduo/member/content/dto/MemberContentDetailDto.java
  src/main/java/com/workduo/member/content/dto/MemberContentDto.java
  src/main/java/com/workduo/member/content/dto/MemberContentListDto.java
  src/main/java/com/workduo/member/content/repository/query/MemberContentQueryRepository.java
  src/main/java/com/workduo/member/content/repository/query/impl/MemberContentQueryRepositoryImpl.java
  src/main/java/com/workduo/member/content/service/MemberContentService.java
  src/main/java/com/workduo/member/content/service/impl/MemberContentServiceImpl.java
  src/test/java/com/workduo/error/global/handler/GlobalExceptionHandlerTest.java
  src/test/java/com/workduo/member/content/controller/MemberContentControllerTest.java
  src/test/java/com/workduo/member/content/service/impl/MemberContentServiceImplTest.java
Labels: ☘️ 기능추가, 🐛 Bug, 🚀코드개선(효율성), 🌈 테스트 코드 작성

#34 그룹 피드 댓글 좋아요, 좋아요 취소 기능 구현
  src/main/java/com/workduo/area/common/controller/AreaController.java
  src/main/java/com/workduo/common/CommonResponse.java
  src/main/java/com/workduo/group/gropcontent/controller/GroupContentController.java
  src/main/java/com/workduo/group/gropcontent/repository/GroupContentCommentLikeRepository.java
  src/main/java/com/workduo/group/gropcontent/repository/GroupContentCommentRepository.java
  src/main/java/com/workduo/group/gropcontent/service/GroupContentService.java
  src/main/java/com/workduo/group/gropcontent/service/impl/GroupContentServiceImpl.java
  src/main/java/com/workduo/group/group/controller/GroupController.java
  src/test/java/com/workduo/group/groupcontent/service/GroupContentServiceTest.java
Labels: ☘️ 기능추가, 🌈 테스트 코드 작성

#37 피드 좋아요,좋아요 취소 API 구현
  src/main/java/com/workduo/error/member/type/MemberErrorCode.java
  src/main/java/com/workduo/member/content/controller/MemberContentController.java
  src/main/java/com/workduo/member/content/repository/MemberContentLikeRepository.java
  src/main/java/com/workduo/member/content/repository/query/impl/MemberContentQueryRepositoryImpl.java
  src/main/java/com/workduo/member/content/service/MemberContentService.java
  src/main/java/com/workduo/member/content/service/impl/MemberContentServiceImpl.java
  src/test/java/com/workduo/member/content/controller/MemberContentControllerTest.java
  src/test/java/com/workduo/member/content/service/impl/MemberContentServiceImplTest.java
Labels: ☘️ 기능추가, 🌈 테스트 코드 작성

#38 Gyubin
  src/main/java/com/workduo/configuration/aop/groupmeeting/GroupMeetingLock.java
  src/main/java/com/workduo/configuration/aop/groupmeeting/GroupMeetingLockAopAspect.java
  src/main/java/com/workduo/configuration/aop/groupmeeting/GroupMeetingLockService.java
  src/main/java/com/workduo/configuration/querydsl/CustomMySQL8InnoDBDialect.java
  src/main/java/com/workduo/error/global/type/GlobalExceptionType.java
  src/main/java/com/workduo/error/group/type/GroupErrorCode.java
  src/main/java/com/workduo/group/group/service/impl/GroupServiceImpl.java
  src/main/java/com/workduo/group/groupmeetingparticipant/controller/GroupMeetingParticipantController.java
  src/main/java/com/workduo/group/groupmeetingparticipant/dto/createGroupMeetingParticipant/CreateParticipant.java
  src/main/java/com/workduo/group/groupmeetingparticipant/dto/createGroupMeetingParticipant/CreateParticipantDto.java
  src/main/java/com/workduo/group/groupmeetingparticipant/service/GroupMeetingParticipantService.java
  src/main/java/com/workduo/group/groupmeetingparticipant/service/impl/GroupMeetingParticipantServiceImpl.java
  src/main/java/com/workduo/group/groupmetting/controller/GroupMeetingController.java
  src/main/java/com/workduo/group/groupmetting/dto/CreateMeeting.java
  src/main/java/com/workduo/group/groupmetting/dto/MeetingInquireDto.java
  src/main/java/com/workduo/group/groupmetting/dto/Time.java
  src/main/java/com/workduo/group/groupmetting/dto/TimeDto.java
  src/main/java/com/workduo/group/groupmetting/entity/GroupMeeting.java
  src/main/java/com/workduo/group/groupmetting/entity/GroupMeetingParticipant.java
  src/main/java/com/workduo/group/groupmetting/repository/GroupMeetingParticipantRepository.java
  src/main/java/com/workduo/group/groupmetting/repository/query/GroupMeetingQueryRepository.java
  src/main/java/com/workduo/group/groupmetting/repository/query/impl/GroupMeetingQueryRepositoryImpl.java
  src/main/java/com/workduo/group/groupmetting/service/GroupMeetingService.java
  src/main/java/com/workduo/group/groupmetting/service/impl/GroupMeetingServiceImpl.java
  src/main/java/com/workduo/member/member/service/impl/MemberServiceImpl.java
  src/main/java/com/workduo/util/AwsS3Utils.java
  src/main/resources/application.yml
  src/test/java/com/workduo/group/group/service/GroupServiceTest.java
  src/test/java/com/workduo/group/groupmeeting/GroupMeetingRepositoryTest.java
  src/test/java/com/workduo/member/member/service/impl/MemberServiceImplTest.java
Labels: ☘️ 기능추가

#39 멤버 피드 댓글 등록 API 구현
  src/main/java/com/workduo/member/content/controller/MemberContentController.java
  src/main/java/com/workduo/member/content/dto/ContentCommentCreate.java
  src/main/java/com/workduo/member/content/service/MemberContentService.java
  src/main/java/com/workduo/member/content/service/impl/MemberContentServiceImpl.java
  src/test/java/com/workduo/member/content/controller/MemberContentControllerTest.java
  src/test/java/com/workduo/member/content/service/impl/MemberContentServiceImplTest.java
Labels: ☘️ 기능추가, 🌈 테스트 코드 작성

#41 멤버 피드 댓글 CRUD,좋아요,좋아요 취소
  src/main/java/com/workduo/error/member/type/MemberErrorCode.java
  src/main/java/com/workduo/member/content/controller/MemberContentController.java
  src/main/java/com/workduo/member/content/dto/ContentCommentList.java
  src/main/java/com/workduo/member/content/dto/ContentCommentUpdate.java
  src/main/java/com/workduo/member/content/dto/MemberContentCommentDto.java
  src/main/java/com/workduo/member/content/entity/MemberContentComment.java
  src/main/java/com/workduo/member/content/repository/MemberContentCommentRepository.java
  src/main/java/com/workduo/member/content/repository/query/impl/MemberContentQueryRepositoryImpl.java
  src/main/java/com/workduo/member/content/service/MemberContentService.java
  src/main/java/com/workduo/member/content/service/impl/MemberContentServiceImpl.java
  src/test/java/com/workduo/member/content/controller/MemberContentControllerTest.java
  src/test/java/com/workduo/member/content/service/impl/MemberContentServiceImplTest.java
Labels: ☘️ 기능추가, 🌈 테스트 코드 작성

#46 그룹 모임 참여자 리스트 기능 구현
  src/main/java/com/workduo/error/global/handler/GlobalExceptionHandler.java
  src/main/java/com/workduo/group/gropcontent/controller/GroupContentController.java
  src/main/java/com/workduo/group/group/controller/GroupController.java
  src/main/java/com/workduo/group/groupmetting/controller/GroupMeetingController.java
  src/main/java/com/workduo/group/groupmetting/dto/CreateMeeting.java
  src/main/java/com/workduo/group/groupmetting/dto/ParticipantDto.java
  src/main/java/com/workduo/group/groupmetting/repository/GroupMeetingParticipantRepository.java
  src/main/java/com/workduo/group/groupmetting/service/GroupMeetingService.java
  src/main/java/com/workduo/group/groupmetting/service/impl/GroupMeetingServiceImpl.java
Labels: ☘️ 기능추가, 🚀코드개선(가독성), 🚀코드개선(효율성)
