Repository WorkDuo/WorkDuo_dev, pull requests merged in 2022-10, with the labels that each got.

#48 리팩토링 (쿼리 최적화), 멤버 수정 api (aws s3 코드 추가)
  src/main/java/com/workduo/configuration/jwt/memberrefreshtoken/repository/MemberRefreshTokenRepository.java
  src/main/java/com/workduo/error/global/exception/CustomMethodArgumentNotValidException.java
  src/main/java/com/workduo/error/global/exception/CustomS3Exception.java
  src/main/java/com/workduo/error/global/handler/GlobalExceptionHandler.java
  src/main/java/com/workduo/group/gropcontent/service/impl/GroupContentServiceImpl.java
  src/main/java/com/workduo/group/group/service/impl/GroupServiceImpl.java
  src/main/java/com/workduo/group/groupmetting/repository/GroupMeetingParticipantRepository.java
  src/main/java/com/workduo/member/content/controller/MemberContentController.java
  src/main/java/com/workduo/member/content/service/impl/MemberContentServiceImpl.java
  src/main/java/com/workduo/member/member/controller/MemberController.java
  src/main/java/com/workduo/member/member/entity/Member.java
  src/main/java/com/workduo/member/member/repository/ExistMemberRepository.java
  src/main/java/com/workduo/member/member/repository/InterestedSportRepository.java
  src/main/java/com/workduo/member/member/repository/MemberActiveAreaRepository.java
  src/main/java/com/workduo/member/member/repository/MemberRepository.java
  src/main/java/com/workduo/member/member/repository/MemberRoleRepository.java
  src/main/java/com/workduo/member/member/service/MemberService.java
  src/main/java/com/workduo/member/member/service/impl/MemberServiceImpl.java
  src/main/java/com/workduo/member/membercalendar/repository/MemberCalendarRepository.java
  src/main/java/com/workduo/util/AwsS3Provider.java
  src/test/java/com/workduo/group/group/service/GroupServiceTest.java
  src/test/java/com/workduo/group/groupcontent/service/GroupContentServiceTest.java
  src/test/java/com/workduo/member/content/service/impl/MemberContentServiceImplTest.java
  src/test/java/com/workduo/member/member/controller/MemberControllerTest.java
  src/test/java/com/workduo/member/member/service/impl/MemberServiceImplTest.java
  src/test/java/com/workduo/member/membercalendar/controller/MemberCalendarControllerTest.java
  src/test/java/com/workduo/member/membercalendar/service/MemberCalendarServiceImplTest.java
Labels: ☘️ 기능추가, 🚀코드개선(가독성), 🚀코드개선(효율성), 🌈 테스트 코드 작성

#49 그룹 썸네일 수정, 그룹 소개, 정원 수정 기능 추가
  src/main/java/com/workduo/error/group/type/GroupErrorCode.java
  src/main/java/com/workduo/group/group/controller/GroupController.java
  src/main/java/com/workduo/group/group/dto/GroupThumbnail.java
  src/main/java/com/workduo/group/group/dto/UpdateGroup.java
  src/main/java/com/workduo/group/group/entity/Group.java
  src/main/java/com/workduo/group/group/service/GroupService.java
  src/main/java/com/workduo/group/group/service/impl/GroupServiceImpl.java
Labels: ☘️ 기능추가

#52 Readme.md 수정, image Update api 분리
  README.md
  src/main/java/com/workduo/member/member/controller/MemberController.java
  src/main/java/com/workduo/member/member/entity/Member.java
  src/main/java/com/workduo/member/member/service/MemberService.java
  src/main/java/com/workduo/member/member/service/impl/MemberServiceImpl.java
  src/test/java/com/workduo/member/member/controller/MemberControllerTest.java
  src/test/java/com/workduo/member/member/service/impl/MemberServiceImplTest.java
  workduo_img.png
Labels: ☘️ 기능추가, 🚀코드개선(가독성), 🚀코드개선(효율성)

#55 EC2 배포 완료
  README.md
Labels: ☘️ 기능추가
